gin:
  mode: debug #gin 开发模式
  port: :3000 #http服务端口
mysql:
  host: localhost:3306
  username: root
  password: 123456
  database: lazy_doc
  log-level: 4
log:
  disable-caller: false
  disable-stacktrace: false
  level: debug
  format: console
  output-paths: [/tmp/lazydoc.log, stdout]
