// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package storage

import (
	"database/sql"
	"time"
)

type Project struct {
	ID                 int64
	ProjectName        string
	ProjectDescription sql.NullString
	IsPublic           sql.NullBool
	IsDeleted          sql.NullBool
	CreatedBy          int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
