// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: tag.sql

package storage

import (
	"context"
)

const getTag = `-- name: GetTag :one
SELECT id, tag_name, created_at, updated_at FROM tag WHERE id = ? LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TagName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
